<?php
/**
 * TGMAX — primary navigation menu.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Categories: Cronaca, Politica, Sport, Cultura, Territorio
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<nav class="primary-navigation" aria-label="Primary">
  <ul class="menu">
        <li class="menu-item"><a href="/">Home</a></li>
        <li class="menu-item"><a href="/category/cronaca">Cronaca</a></li>
        <li class="menu-item"><a href="/category/sport">Sport</a></li>
        <li class="menu-item"><a href="/dirette">Dirette</a></li>
  </ul>
</nav>
