/**
 * Knowledge Engine integration. Seeds a Knowledge service with the landing-page
 * naming conventions and exposes a Generator Engine transform that retrieves them
 * via full-text search — a real ingest → index → retrieval round-trip.
 */
import { ServiceContainer, err, isErr, ok } from "@telemax/core";
import { registerKnowledge, type KnowledgeService } from "@telemax/knowledge";
import { GeneratorStepError, type GeneratorTransform } from "@telemax/generator-engine";

/** The naming-conventions document stored in and served from the Knowledge Engine. */
export const LANDING_CONVENTIONS_DOC = `# Naming conventions

Generated by Telemax AI Factory — Landing Page generator.

## Files

- The page entry point is \`index.html\` at the project root.
- Styles live under \`assets/css/\` (\`tokens.css\` for design tokens, \`style.css\`
  for layout and components).
- Scripts live under \`assets/js/\` (\`main.js\`).
- Images live under \`assets/images/\`.
- Machine-readable configuration lives under \`config/\` (\`content-plan.json\`,
  \`design-tokens.json\`).

## Identifiers

- Section ids are lowercase, hyphen-separated, and used as in-page anchors
  (\`#about\`, \`#services\`, \`#contact\`).
- CSS classes are hyphen-separated (\`hero-title\`, \`section-body\`, \`cta-button\`).
- The in-page navigation links to section ids only (no external routing).

## Content

- The page is a single scrollable document: hero, then content sections, then
  footer. No multi-page routing.
- Copy is plain text; no inline HTML, scripts or styles from the content source.
`;

/** Build a Knowledge service seeded with the naming-conventions document. */
export async function seedKnowledge(): Promise<KnowledgeService> {
  const service = registerKnowledge(new ServiceContainer());
  await service.addDocument({ format: "markdown", content: LANDING_CONVENTIONS_DOC });
  return service;
}

/** Retrieve the naming-conventions text from the Knowledge Engine (full-text search). */
export async function getConventions(service: KnowledgeService): Promise<string> {
  const hits = await service.search({ text: "naming conventions", limit: 1 });
  if (isErr(hits)) return LANDING_CONVENTIONS_DOC;
  const first = hits.value[0];
  if (first === undefined) return LANDING_CONVENTIONS_DOC;
  const document = await service.getDocument(first.documentId);
  return isErr(document) ? LANDING_CONVENTIONS_DOC : document.value.content;
}

/** A transform that returns the naming conventions retrieved from the Knowledge Engine. */
export function conventionsTransform(service: KnowledgeService): GeneratorTransform {
  return async () => {
    const hits = await service.search({ text: "naming conventions", limit: 1 });
    if (isErr(hits)) {
      return err(
        new GeneratorStepError(hits.error.message, "lp-conventions", { cause: hits.error }),
      );
    }
    const first = hits.value[0];
    if (first === undefined) {
      return ok(LANDING_CONVENTIONS_DOC);
    }
    const document = await service.getDocument(first.documentId);
    if (isErr(document)) {
      return err(
        new GeneratorStepError(document.error.message, "lp-conventions", { cause: document.error }),
      );
    }
    return ok(document.value.content);
  };
}
