<?php
/**
 * Gruppo AIR Blog — in-article ad slot.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — wire your ad manager during completion.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<div class="ad-slot ad-in-article" data-ad-slot="in-article">
  <!-- TODO: inject ad tag for the "in-article" slot -->
</div>
