<?php
/**
 * Gruppo AIR Blog — leaderboard ad slot.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — wire your ad manager during completion.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<div class="ad-slot ad-leaderboard" data-ad-slot="leaderboard">
  <!-- TODO: inject ad tag for the "leaderboard" slot -->
</div>
