<?php
/**
 * Vivere Magazine — component: Breadcrumb.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Category: meta · Regions: content.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<section class="c-breadcrumb" data-component="breadcrumb" role="navigation" aria-label="Breadcrumb">
  <meta itemprop="type" content="BreadcrumbList" />
  <!-- TODO: implement the "Breadcrumb" component -->
</section>
