/**
 * Knowledge Engine integration. Seeds a Knowledge service with the project naming
 * conventions and exposes a Generator Engine transform that retrieves them via
 * full-text search — a real ingest → index → retrieval round-trip.
 */
import { ServiceContainer, err, isErr, ok } from "@telemax/core";
import { registerKnowledge, type KnowledgeService } from "@telemax/knowledge";
import { GeneratorStepError, type GeneratorTransform } from "@telemax/generator-engine";

/** The naming-conventions document stored in and served from the Knowledge Engine. */
export const NAMING_CONVENTIONS_DOC = `# Naming conventions

Generated by Telemax AI Factory — WordPress News generator.

## Files & templates

- Template files use WordPress core names: \`single.php\`, \`category.php\`,
  \`archive.php\`, \`front-page.php\`.
- Reusable fragments live under \`template-parts/\` grouped by concern
  (\`ads/\`, \`seo/\`, \`schema/\`).
- Includes live under \`inc/\` (\`seo.php\`, \`schema.php\`, \`widgets.php\`,
  \`sitemap.php\`).

## Identifiers

- Text domain and theme slug are lowercase, hyphen-separated.
- CSS classes are hyphen-separated (\`article-title\`, \`site-header\`).
- Widget area ids are hyphen-separated (\`sidebar-main\`, \`footer-1\`).
- Ad slot ids match their location (\`leaderboard\`, \`sidebar\`, \`in-article\`).

## Assets

- Images live under \`assets/images/\` in \`logos/\`, \`icons/\`, \`placeholders/\`.
- Icon files follow \`icon-<size>.png\` (e.g. \`icon-192.png\`).
`;

/** Build a Knowledge service seeded with the naming-conventions document. */
export async function seedKnowledge(): Promise<KnowledgeService> {
  const service = registerKnowledge(new ServiceContainer());
  await service.addDocument({ format: "markdown", content: NAMING_CONVENTIONS_DOC });
  return service;
}

/** Retrieve the naming-conventions text from the Knowledge Engine (full-text search). */
export async function getConventions(service: KnowledgeService): Promise<string> {
  const hits = await service.search({ text: "naming conventions", limit: 1 });
  if (isErr(hits)) return NAMING_CONVENTIONS_DOC;
  const first = hits.value[0];
  if (first === undefined) return NAMING_CONVENTIONS_DOC;
  const document = await service.getDocument(first.documentId);
  return isErr(document) ? NAMING_CONVENTIONS_DOC : document.value.content;
}

/** A transform that returns the naming conventions retrieved from the Knowledge Engine. */
export function conventionsTransform(service: KnowledgeService): GeneratorTransform {
  return async () => {
    const hits = await service.search({ text: "naming conventions", limit: 1 });
    if (isErr(hits)) {
      return err(
        new GeneratorStepError(hits.error.message, "wp-conventions", { cause: hits.error }),
      );
    }
    const first = hits.value[0];
    if (first === undefined) {
      return ok(NAMING_CONVENTIONS_DOC);
    }
    const document = await service.getDocument(first.documentId);
    if (isErr(document)) {
      return err(
        new GeneratorStepError(document.error.message, "wp-conventions", { cause: document.error }),
      );
    }
    return ok(document.value.content);
  };
}
