<?php
/**
 * Il Corriere della Sera Nuovo — 404 not found.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Generated at: 2026-08-01T12:00:00.000Z · Artifact metadata is catalogued in .telemax/manifest.json.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>
<main class="site-container error-404">
  <section class="not-found">
    <h1>404 — Page not found</h1>
    <p>The page you were looking for is not here.</p>
    <?php get_search_form(); ?>
    <p><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Back to the homepage</a></p>
  </section>
</main>
<?php get_footer(); ?>
