<?php
/**
 * Il Corriere della Sera Nuovo — author archive.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Generated at: 2026-08-01T12:00:00.000Z · Artifact metadata is catalogued in .telemax/manifest.json.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>
<main class="site-container author-archive">
  <header class="author-header">
    <h1><?php the_archive_title(); ?></h1>
    <p class="author-bio"><?php the_archive_description(); ?></p>
  </header>
  <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <article <?php post_class(); ?>>
      <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
    </article>
  <?php endwhile; endif; ?>
  <?php the_posts_pagination(); ?>
  <?php get_sidebar(); ?>
</main>
<?php get_footer(); ?>
