<?php
/**
 * Il Corriere della Sera Nuovo — category layout.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>
<main class="site-container">
  <header class="category-header"><h1><?php single_cat_title(); ?></h1></header>
  <div class="category-grid">
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
      <article <?php post_class(); ?>>
        <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
      </article>
    <?php endwhile; endif; ?>
  </div>
  <?php get_sidebar(); ?>
</main>
<?php get_footer(); ?>
