<?php
/**
 * Il Corriere della Sera Nuovo — homepage layout.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>
<main class="site-container home">
  <?php get_template_part( 'template-parts/ads/ad-leaderboard' ); ?>
  <section class="lead-stories"><!-- TODO: featured story loop --></section>
  <div class="home-grid">
    <section class="latest-news"><!-- TODO: latest posts loop --></section>
    <?php get_sidebar(); ?>
  </div>
</main>
<?php get_footer(); ?>
