<?php
/**
 * Gruppo AIR Blog — search results.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Generated at: 2026-08-01T12:00:00.000Z · Artifact metadata is catalogued in .telemax/manifest.json.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>
<main class="site-container search-results">
  <header class="page-heading">
    <h1><?php printf( esc_html__( 'Search results for: %s', 'gruppo-air-blog' ), get_search_query() ); ?></h1>
  </header>
  <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <article <?php post_class( 'search-hit' ); ?>>
      <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
      <?php the_excerpt(); ?>
    </article>
  <?php endwhile; else : ?>
    <p class="empty">Nothing found. Try another query.</p>
  <?php endif; ?>
  <?php the_posts_pagination(); ?>
</main>
<?php get_footer(); ?>
