<?php
/**
 * Sprint Sport — primary navigation menu.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Categories: Calcio, Motori, Basket, Tennis, Calciomercato, Live
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<nav class="primary-navigation" aria-label="Primary">
  <ul class="menu">
        <li class="menu-item"><a href="/">Home</a></li>
        <li class="menu-item"><a href="/category/calcio">Calcio</a></li>
        <li class="menu-item"><a href="/live">Live</a></li>
        <li class="menu-item"><a href="/category/calciomercato">Calciomercato</a></li>
  </ul>
</nav>
