/** Generated project README. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export const docsTemplates: readonly GeneratorTemplate[] = [
  {
    id: "lp.readme",
    name: "README.md",
    contentType: "text/markdown",
    body: `# {{siteName}}

{{tagline}}

Static single-page landing site generated by **Telemax AI Factory** — Landing Page
generator v{{generatorVersion}} on {{generatedAt}}.

## Usage

Open \`index.html\` directly in a browser, or serve the folder with any static
file server. No build step is required.

## Structure

- \`index.html\` — the page.
- \`assets/css/tokens.css\` — design tokens (CSS custom properties).
- \`assets/css/style.css\` — layout and components.
- \`assets/js/main.js\` — small progressive enhancement.
- \`config/content-plan.json\` — the validated Content Plan the copy was rendered
  from, with its \`source\` (\`ai\` or \`fallback\`) and \`validation\` provenance.
- \`config/design-tokens.json\` — the design tokens as JSON.
- \`.telemax/manifest.json\` — per-file checksums and version.

Site URL: {{siteUrl}}

> PROJECT SCAFFOLD — review the copy before publishing.
`,
  },
];
