/** The single HTML page produced by the Landing Page generator. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export const pageTemplates: readonly GeneratorTemplate[] = [
  {
    id: "lp.index",
    name: "index.html",
    contentType: "text/html",
    body: `<!DOCTYPE html>
<html lang="{{language}}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{{seoTitle}}</title>
  <meta name="description" content="{{metaDescription}}" />
  <meta name="keywords" content="{{keywordsList}}" />
  <meta name="generator" content="Telemax AI Factory · Landing Page generator v{{generatorVersion}}" />
  <meta property="og:title" content="{{seoTitle}}" />
  <meta property="og:description" content="{{metaDescription}}" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="{{siteUrl}}" />
  <link rel="stylesheet" href="assets/css/tokens.css" />
  <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body>
  <!--
    {{siteName}} — landing page.
    Generated by Telemax AI Factory · Landing Page generator v{{generatorVersion}}.
    Generated at: {{generatedAt}} · Artifact metadata is catalogued in .telemax/manifest.json.
    PROJECT SCAFFOLD — review the copy before publishing.
  -->
  <header class="site-header">
    <div class="site-container header-inner">
      <a class="brand" href="#top">{{siteName}}</a>
      <nav class="site-nav" aria-label="Primary">
{{navHtml}}
      </nav>
    </div>
  </header>

  <main id="top">
    <section class="hero">
      <div class="site-container">
        <h1 class="hero-title">{{heroHeadline}}</h1>
        <p class="hero-subtitle">{{heroSubheadline}}</p>
        <a class="cta-button" href="{{ctaHref}}">{{ctaLabel}}</a>
      </div>
    </section>

    <div class="site-container content">
{{featuresHtml}}
{{sectionsHtml}}
    </div>
  </main>

  <footer class="site-footer">
    <div class="site-container">
      <p class="footer-tagline">{{footerTagline}}</p>
      <p class="footer-meta">{{year}} · Generated by Telemax AI Factory v{{generatorVersion}}</p>
    </div>
  </footer>

  <script src="assets/js/main.js"></script>
</body>
</html>
`,
  },
];
