/** Tiny progressive-enhancement script for the landing page. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export const scriptTemplates: readonly GeneratorTemplate[] = [
  {
    id: "lp.script",
    name: "assets/js/main.js",
    contentType: "text/javascript",
    body: `/*
 * {{siteName}} — main script.
 * Generated by Telemax AI Factory · Landing Page generator v{{generatorVersion}}.
 * Generated at: {{generatedAt}}
 */
(function () {
  "use strict";
  document.addEventListener("DOMContentLoaded", function () {
    document.documentElement.classList.add("js");
    // Highlight the in-page nav link for the section currently in view.
    var links = Array.prototype.slice.call(document.querySelectorAll(".site-nav a[href^='#']"));
    if (links.length === 0 || !("IntersectionObserver" in window)) return;
    var byId = {};
    links.forEach(function (link) { byId[link.getAttribute("href").slice(1)] = link; });
    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        var link = byId[entry.target.id];
        if (link) link.classList.toggle("is-active", entry.isIntersecting);
      });
    }, { rootMargin: "-40% 0px -55% 0px" });
    Object.keys(byId).forEach(function (id) {
      var el = document.getElementById(id);
      if (el) observer.observe(el);
    });
  });
})();
`,
  },
];
