/** Generated stylesheet for the landing page (layout + components). */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export const styleTemplates: readonly GeneratorTemplate[] = [
  {
    id: "lp.style",
    name: "assets/css/style.css",
    contentType: "text/css",
    body: `/*
 * {{siteName}} — landing page stylesheet.
 * Generated by Telemax AI Factory · Landing Page generator v{{generatorVersion}}.
 * Generated at: {{generatedAt}}
 * Design tokens are declared in tokens.css.
 */
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0;
  font-family: var(--font-body);
  font-size: var(--font-size-base);
  line-height: 1.6;
  color: var(--color-text);
  background: var(--color-background);
}
a { color: var(--color-primary); }
h1, h2, h3 { font-family: var(--font-heading); line-height: 1.15; color: var(--color-secondary); }

.site-container { max-width: 1080px; margin: 0 auto; padding: 0 var(--space-lg); }

.site-header { border-bottom: 1px solid var(--color-border); background: var(--color-background); }
.header-inner { display: flex; align-items: center; justify-content: space-between; padding: var(--space-md) 0; }
.brand { font-weight: 700; text-decoration: none; color: var(--color-secondary); }
.site-nav { display: flex; gap: var(--space-lg); flex-wrap: wrap; }
.site-nav a { text-decoration: none; color: var(--color-text-muted); }
.site-nav a:hover { color: var(--color-primary); }

.hero { padding: var(--space-3xl) 0; background: var(--color-surface); text-align: center; }
.hero-title { font-size: var(--font-size-4xl); margin: 0 0 var(--space-md); }
.hero-subtitle { font-size: var(--font-size-lg); color: var(--color-text-muted); max-width: 42rem; margin: 0 auto var(--space-xl); }
.cta-button {
  display: inline-block;
  padding: var(--space-md) var(--space-xl);
  background: var(--color-primary);
  color: var(--color-on-primary);
  border-radius: 8px;
  text-decoration: none;
  font-weight: 600;
}

.content { padding: var(--space-3xl) 0; display: grid; gap: var(--space-2xl); }
.section-title { font-size: var(--font-size-2xl); margin: 0 0 var(--space-sm); }
.section-body { color: var(--color-text-muted); margin: 0; }

.feature-grid { list-style: none; padding: 0; margin: 0; display: grid; gap: var(--space-lg); grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); }
.feature-card { padding: var(--space-lg); border: 1px solid var(--color-border); border-radius: 8px; background: var(--color-surface); }
.feature-title { font-size: var(--font-size-lg); margin: 0 0 var(--space-xs); }
.feature-description { color: var(--color-text-muted); margin: 0; }

.site-footer { border-top: 1px solid var(--color-border); padding: var(--space-xl) 0; text-align: center; color: var(--color-text-muted); }
.footer-tagline { margin: 0 0 var(--space-xs); }
.footer-meta { margin: 0; font-size: var(--font-size-sm); }

@media (max-width: 640px) {
  .hero-title { font-size: var(--font-size-3xl); }
  .header-inner { flex-direction: column; gap: var(--space-sm); }
}
`,
  },
];
