/** Advertising blocks, ad configuration and widget areas. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

function adBlock(role: string): string {
  return `<?php
/**
 * {{themeName}} — ${role} ad slot.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * PROJECT SCAFFOLD — wire your ad manager during completion.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<div class="ad-slot ad-${role}" data-ad-slot="${role}">
  <!-- TODO: inject ad tag for the "${role}" slot -->
</div>
`;
}

export const adsTemplates: readonly GeneratorTemplate[] = [
  {
    id: "wp.ad-leaderboard",
    name: "template-parts/ads/ad-leaderboard.php",
    contentType: "application/x-php",
    body: adBlock("leaderboard"),
  },
  {
    id: "wp.ad-sidebar",
    name: "template-parts/ads/ad-sidebar.php",
    contentType: "application/x-php",
    body: adBlock("sidebar"),
  },
  {
    id: "wp.ad-in-article",
    name: "template-parts/ads/ad-in-article.php",
    contentType: "application/x-php",
    body: adBlock("in-article"),
  },
  {
    id: "wp.ads-config",
    name: "config/ads.config.json",
    contentType: "application/json",
    body: `{
  "generatedBy": "Telemax AI Factory",
  "generatorVersion": "{{generatorVersion}}",
  "slots": {{adSlotsJson}}
}
`,
  },
  {
    id: "wp.widgets",
    name: "inc/widgets.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — widget areas.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * Registered areas: {{widgetAreasList}}
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'widgets_init', function () {
  $areas = array( 'sidebar-main', 'footer-1', 'footer-2', 'footer-3' );
  foreach ( $areas as $area ) {
    register_sidebar( array(
      'id'   => $area,
      'name' => ucwords( str_replace( '-', ' ', $area ) ),
    ) );
  }
} );
`,
  },
];
