/** Generated front-end assets: main stylesheet, main script, theme screenshot. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export const assetTemplates: readonly GeneratorTemplate[] = [
  {
    id: "wp.main-css",
    name: "assets/css/main.css",
    contentType: "text/css",
    body: `/*
 * {{themeName}} — main stylesheet.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * Generated at: {{generatedAt}}
 */
:root {
  --color-primary: {{primaryColor}};
  --color-secondary: {{secondaryColor}};
  --container: 1200px;
}
* { box-sizing: border-box; }
body { margin: 0; font-family: Georgia, "Times New Roman", serif; color: #111; line-height: 1.6; }
.site-container { max-width: var(--container); margin: 0 auto; padding: 0 16px; }
.site-header { border-bottom: 3px solid var(--color-primary); }
.article-title { color: var(--color-secondary); }
.article-title a { text-decoration: none; color: inherit; }
.posts-river { display: grid; gap: 24px; }
.error-404 .not-found { text-align: center; padding: 64px 0; }
`,
  },
  {
    id: "wp.main-js",
    name: "assets/js/main.js",
    contentType: "text/javascript",
    body: `/*
 * {{themeName}} — main script.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * Generated at: {{generatedAt}}
 */
(function () {
  "use strict";
  document.addEventListener("DOMContentLoaded", function () {
    document.documentElement.classList.add("js");
    // TODO: progressive enhancements (menu toggle, lazy embeds) on completion.
  });
})();
`,
  },
  {
    id: "wp.screenshot",
    name: "screenshot.svg",
    contentType: "image/svg+xml",
    body: `<?xml version="1.0" encoding="UTF-8"?>
<!--
  {{themeName}} — theme screenshot placeholder.
  Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
  Replace with a 1200x900 screenshot.png before publishing.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="900" viewBox="0 0 1200 900">
  <rect width="1200" height="900" fill="{{secondaryColor}}"/>
  <rect x="0" y="0" width="1200" height="120" fill="{{primaryColor}}"/>
  <text x="60" y="80" font-family="Arial, sans-serif" font-size="48" fill="#ffffff">{{siteName}}</text>
  <text x="60" y="480" font-family="Arial, sans-serif" font-size="32" fill="#ffffff">WordPress News theme</text>
  <text x="60" y="540" font-family="Arial, sans-serif" font-size="24" fill="#e2e2e2">Generated by Telemax AI Factory · v{{generatorVersion}}</text>
</svg>
`,
  },
];
