/** Project documentation artifacts: README, STRUCTURE, PROJECT. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export const docsTemplates: readonly GeneratorTemplate[] = [
  {
    id: "wp.readme",
    name: "README.md",
    contentType: "text/markdown",
    body: `# {{themeName}}

News theme **project scaffold** generated by Telemax AI Factory — WordPress News
generator v{{generatorVersion}}.

> This is a project scaffold, **not** production WordPress code and **not** a
> plugin. Review, complete and test every file before deploying.

- **Site:** {{siteName}} — {{siteDescription}}
- **URL:** {{siteUrl}}
- **Language:** {{language}}
- **Categories:** {{categoriesList}}

See [\`docs/PROJECT.md\`](docs/PROJECT.md) and [\`STRUCTURE.md\`](STRUCTURE.md).
`,
  },
  {
    id: "wp.structure",
    name: "STRUCTURE.md",
    contentType: "text/markdown",
    body: `# {{themeName}} — project structure

\`\`\`
{{themeSlug}}/
├── style.css                 Theme metadata + scaffold styles
├── theme.json                Block theme settings
├── functions.php             Theme bootstrap (includes inc/*)
├── front-page.php            Homepage layout
├── index.php                 Blog index fallback
├── single.php                Single article layout
├── category.php              Category layout
├── archive.php               Archive layout
├── page.php                  Static page layout
├── header.php                Site header
├── footer.php                Site footer
├── sidebar.php               Primary sidebar
├── robots.txt                Crawler directives
├── manifest.webmanifest      Web app manifest
├── config/
│   ├── ads.config.json       Ad slot configuration
│   └── sitemap.config.json   Sitemap configuration
├── inc/
│   ├── seo.php               SEO helpers
│   ├── schema.php            Schema.org (NewsMediaOrganization)
│   ├── widgets.php           Widget areas
│   └── sitemap.php           Sitemap configuration
├── template-parts/
│   ├── navigation.php        Primary menu
│   ├── ads/                  Ad blocks (leaderboard, sidebar, in-article)
│   ├── seo/meta-tags.php     Open Graph / Twitter tags
│   └── schema/newsarticle.php NewsArticle JSON-LD
├── assets/images/            logos, icons, placeholders
└── docs/
    ├── PROJECT.md            Project overview
    └── NAMING-CONVENTIONS.md Naming conventions (from Knowledge Engine)
\`\`\`
`,
  },
  {
    id: "wp.project-doc",
    name: "docs/PROJECT.md",
    contentType: "text/markdown",
    body: `# {{themeName}} — project overview

Generated by Telemax AI Factory (WordPress News generator v{{generatorVersion}}),
authored on the generic Generator Engine and coordinated with the Workflow, Prompt
and Knowledge engines.

## What is generated

A complete WordPress News **theme project structure** as artifacts: configuration,
page layouts, structural partials, advertising blocks, widget areas, SEO and
Schema.org components, \`robots.txt\`, sitemap and manifest configuration, an image
directory layout, naming conventions and this documentation.

## Integrations

- **Workflow Engine** — a prepare workflow computes the build metadata written to
  \`.telemax/build-info.json\`.
- **Prompt Engine** — renders the site meta description used by the SEO components.
- **Knowledge Engine** — supplies the naming conventions in
  \`docs/NAMING-CONVENTIONS.md\`.

## Not included (by design)

No plugin, no production WordPress code, no build tooling. Every \`.php\` file is a
reviewed-before-use scaffold with \`TODO\` markers.

## Next steps

Complete theme supports and enqueues in \`functions.php\`, wire the ad manager,
finalize SEO/Schema output, and add automated theme checks.
`,
  },
];
