/** Page layout artifacts: homepage, blog index, single article, category, archive, page. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

function phpHeader(role: string): string {
  return `<?php
/**
 * {{themeName}} — ${role}.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>`;
}

export const layoutTemplates: readonly GeneratorTemplate[] = [
  {
    id: "wp.front-page",
    name: "front-page.php",
    contentType: "application/x-php",
    body: `${phpHeader("homepage layout")}
<main class="site-container home">
  <?php get_template_part( 'template-parts/ads/ad-leaderboard' ); ?>
  <section class="lead-stories"><!-- TODO: featured story loop --></section>
  <div class="home-grid">
    <section class="latest-news"><!-- TODO: latest posts loop --></section>
    <?php get_sidebar(); ?>
  </div>
</main>
<?php get_footer(); ?>
`,
  },
  {
    id: "wp.index",
    name: "index.php",
    contentType: "application/x-php",
    body: `${phpHeader("blog index fallback")}
<main class="site-container">
  <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <article <?php post_class(); ?>>
      <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
      <?php the_excerpt(); ?>
    </article>
  <?php endwhile; endif; ?>
</main>
<?php get_footer(); ?>
`,
  },
  {
    id: "wp.single",
    name: "single.php",
    contentType: "application/x-php",
    body: `${phpHeader("single article layout")}
<main class="site-container">
  <?php while ( have_posts() ) : the_post(); ?>
    <article <?php post_class( 'single-article' ); ?>>
      <h1 class="article-title"><?php the_title(); ?></h1>
      <?php get_template_part( 'template-parts/schema/newsarticle' ); ?>
      <div class="article-body"><?php the_content(); ?></div>
      <?php get_template_part( 'template-parts/ads/ad-in-article' ); ?>
    </article>
  <?php endwhile; ?>
  <?php get_sidebar(); ?>
</main>
<?php get_footer(); ?>
`,
  },
  {
    id: "wp.category",
    name: "category.php",
    contentType: "application/x-php",
    body: `${phpHeader("category layout")}
<main class="site-container">
  <header class="category-header"><h1><?php single_cat_title(); ?></h1></header>
  <div class="category-grid">
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
      <article <?php post_class(); ?>>
        <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
      </article>
    <?php endwhile; endif; ?>
  </div>
  <?php get_sidebar(); ?>
</main>
<?php get_footer(); ?>
`,
  },
  {
    id: "wp.archive",
    name: "archive.php",
    contentType: "application/x-php",
    body: `${phpHeader("archive layout")}
<main class="site-container">
  <header class="archive-header"><h1><?php the_archive_title(); ?></h1></header>
  <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <article <?php post_class(); ?>>
      <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
      <?php the_excerpt(); ?>
    </article>
  <?php endwhile; endif; ?>
  <?php the_posts_pagination(); ?>
</main>
<?php get_footer(); ?>
`,
  },
  {
    id: "wp.page",
    name: "page.php",
    contentType: "application/x-php",
    body: `${phpHeader("static page layout")}
<main class="site-container">
  <?php while ( have_posts() ) : the_post(); ?>
    <article <?php post_class( 'static-page' ); ?>>
      <h1 class="article-title"><?php the_title(); ?></h1>
      <div class="page-body"><?php the_content(); ?></div>
    </article>
  <?php endwhile; ?>
</main>
<?php get_footer(); ?>
`,
  },
];
