/** Additional WordPress page templates: home, search, author, 404. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

function phpHeader(role: string): string {
  return `<?php
/**
 * {{themeName}} — ${role}.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * Generated at: {{generatedAt}} · Artifact metadata is catalogued in .telemax/manifest.json.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>`;
}

export const pageTemplates: readonly GeneratorTemplate[] = [
  {
    id: "wp.home",
    name: "home.php",
    contentType: "application/x-php",
    body: `${phpHeader("blog posts index (news river)")}
<main class="site-container home-posts">
  <header class="page-heading"><h1><?php bloginfo( 'name' ); ?> — Latest</h1></header>
  <div class="posts-river">
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
      <article <?php post_class( 'post-card' ); ?>>
        <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
        <?php the_excerpt(); ?>
      </article>
    <?php endwhile; else : ?>
      <p class="empty">No posts yet.</p>
    <?php endif; ?>
  </div>
  <?php the_posts_pagination(); ?>
  <?php get_sidebar(); ?>
</main>
<?php get_footer(); ?>
`,
  },
  {
    id: "wp.search",
    name: "search.php",
    contentType: "application/x-php",
    body: `${phpHeader("search results")}
<main class="site-container search-results">
  <header class="page-heading">
    <h1><?php printf( esc_html__( 'Search results for: %s', '{{themeSlug}}' ), get_search_query() ); ?></h1>
  </header>
  <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <article <?php post_class( 'search-hit' ); ?>>
      <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
      <?php the_excerpt(); ?>
    </article>
  <?php endwhile; else : ?>
    <p class="empty">Nothing found. Try another query.</p>
  <?php endif; ?>
  <?php the_posts_pagination(); ?>
</main>
<?php get_footer(); ?>
`,
  },
  {
    id: "wp.author",
    name: "author.php",
    contentType: "application/x-php",
    body: `${phpHeader("author archive")}
<main class="site-container author-archive">
  <header class="author-header">
    <h1><?php the_archive_title(); ?></h1>
    <p class="author-bio"><?php the_archive_description(); ?></p>
  </header>
  <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <article <?php post_class(); ?>>
      <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
    </article>
  <?php endwhile; endif; ?>
  <?php the_posts_pagination(); ?>
  <?php get_sidebar(); ?>
</main>
<?php get_footer(); ?>
`,
  },
  {
    id: "wp.404",
    name: "404.php",
    contentType: "application/x-php",
    body: `${phpHeader("404 not found")}
<main class="site-container error-404">
  <section class="not-found">
    <h1>404 — Page not found</h1>
    <p>The page you were looking for is not here.</p>
    <?php get_search_form(); ?>
    <p><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Back to the homepage</a></p>
  </section>
</main>
<?php get_footer(); ?>
`,
  },
];
