/** Structural partials: header, footer, sidebar, navigation (menu). */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export const partialTemplates: readonly GeneratorTemplate[] = [
  {
    id: "wp.header",
    name: "header.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — header.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!doctype html>
<html lang="{{language}}" <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo( 'charset' ); ?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <?php get_template_part( 'template-parts/seo/meta-tags' ); ?>
  <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<header class="site-header">
  <div class="site-container">
    <a class="site-brand" href="{{siteUrl}}">{{siteName}}</a>
    <p class="site-tagline">{{siteDescription}}</p>
    <?php get_template_part( 'template-parts/navigation' ); ?>
  </div>
</header>
`,
  },
  {
    id: "wp.footer",
    name: "footer.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — footer.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<footer class="site-footer">
  <div class="site-container">
    <nav class="footer-widgets">
      <?php if ( is_active_sidebar( 'footer-1' ) ) { dynamic_sidebar( 'footer-1' ); } ?>
      <?php if ( is_active_sidebar( 'footer-2' ) ) { dynamic_sidebar( 'footer-2' ); } ?>
      <?php if ( is_active_sidebar( 'footer-3' ) ) { dynamic_sidebar( 'footer-3' ); } ?>
    </nav>
    <p class="copyright">&copy; {{year}} {{siteName}}. All rights reserved.</p>
  </div>
</footer>
<?php wp_footer(); ?>
</body>
</html>
`,
  },
  {
    id: "wp.sidebar",
    name: "sidebar.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — primary sidebar.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<aside class="site-sidebar">
  <?php get_template_part( 'template-parts/ads/ad-sidebar' ); ?>
  <?php if ( is_active_sidebar( 'sidebar-main' ) ) { dynamic_sidebar( 'sidebar-main' ); } ?>
</aside>
`,
  },
  {
    id: "wp.navigation",
    name: "template-parts/navigation.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — primary navigation menu.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * Categories: {{categoriesList}}
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<nav class="primary-navigation" aria-label="Primary">
  <ul class="menu">
{{menuMarkup}}
  </ul>
</nav>
`,
  },
];
