/** SEO components, Schema.org, robots.txt, sitemap configuration and web manifest. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export const seoTemplates: readonly GeneratorTemplate[] = [
  {
    id: "wp.seo",
    name: "inc/seo.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — SEO helpers.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'wp_head', function () {
  $description = is_singular() ? wp_strip_all_tags( get_the_excerpt() ) : '{{metaDescription}}';
  printf( '<meta name="description" content="%s" />' . "\\n", esc_attr( $description ) );
  printf( '<link rel="canonical" href="%s" />' . "\\n", esc_url( home_url( add_query_arg( array() ) ) ) );
}, 1 );
`,
  },
  {
    id: "wp.meta-tags",
    name: "template-parts/seo/meta-tags.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — Open Graph / Twitter meta tags.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<meta property="og:site_name" content="{{siteName}}" />
<meta property="og:type" content="website" />
<meta property="og:description" content="{{metaDescription}}" />
<meta property="og:locale" content="{{language}}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{{siteName}}" />
`,
  },
  {
    id: "wp.schema",
    name: "inc/schema.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — Schema.org helpers (NewsMediaOrganization).
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'wp_head', function () {
  $data = array(
    '@context' => 'https://schema.org',
    '@type'    => 'NewsMediaOrganization',
    'name'     => '{{siteName}}',
    'url'      => '{{siteUrl}}',
  );
  echo '<script type="application/ld+json">' . wp_json_encode( $data ) . '</script>';
} );
`,
  },
  {
    id: "wp.schema-newsarticle",
    name: "template-parts/schema/newsarticle.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — NewsArticle JSON-LD for single posts.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
$schema = array(
  '@context'      => 'https://schema.org',
  '@type'         => 'NewsArticle',
  'headline'      => get_the_title(),
  'datePublished' => get_the_date( 'c' ),
  'dateModified'  => get_the_modified_date( 'c' ),
  'author'        => array( '@type' => 'Person', 'name' => get_the_author() ),
  'publisher'     => array( '@type' => 'Organization', 'name' => '{{siteName}}' ),
);
?>
<script type="application/ld+json"><?php echo wp_json_encode( $schema ); ?></script>
`,
  },
  {
    id: "wp.sitemap",
    name: "inc/sitemap.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — sitemap configuration.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * PROJECT SCAFFOLD — tune the core sitemap provider on completion.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

add_filter( 'wp_sitemaps_max_urls', function () { return 2000; } );
// TODO: register a dedicated news sitemap provider during completion.
`,
  },
  {
    id: "wp.sitemap-config",
    name: "config/sitemap.config.json",
    contentType: "application/json",
    body: `{
  "generatedBy": "Telemax AI Factory",
  "generatorVersion": "{{generatorVersion}}",
  "sitemap": {
    "enabled": true,
    "maxUrls": 2000,
    "news": { "enabled": true, "publication": "{{siteName}}", "language": "{{language}}" }
  }
}
`,
  },
  {
    id: "wp.manifest",
    name: "manifest.webmanifest",
    contentType: "application/manifest+json",
    body: `{
  "name": "{{siteName}}",
  "short_name": "{{themeName}}",
  "description": "{{siteDescription}}",
  "lang": "{{language}}",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "{{primaryColor}}",
  "icons": [
    { "src": "assets/images/icons/icon-192.png", "sizes": "192x192", "type": "image/png" },
    { "src": "assets/images/icons/icon-512.png", "sizes": "512x512", "type": "image/png" }
  ]
}
`,
  },
];
