/** Theme configuration artifacts: style.css, theme.json, functions.php. */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export const themeTemplates: readonly GeneratorTemplate[] = [
  {
    id: "wp.style",
    name: "style.css",
    contentType: "text/css",
    body: `/*
Theme Name: {{themeName}}
Theme URI: {{siteUrl}}
Author: {{author}}
Description: {{siteDescription}}
Version: {{generatorVersion}}
Requires at least: 6.4
Requires PHP: 8.1
License: GPL-2.0-or-later
Text Domain: {{themeSlug}}
Tags: news, magazine, blog
Generated-By: Telemax AI Factory (project scaffold — not production code)
*/

:root {
  --color-primary: {{primaryColor}};
  --color-secondary: {{secondaryColor}};
  --container: 1200px;
}

/* Scaffold styles only — extend during theme completion. */
body { margin: 0; font-family: Georgia, "Times New Roman", serif; color: #111; }
.site-container { max-width: var(--container); margin: 0 auto; padding: 0 16px; }
.site-header { border-bottom: 3px solid var(--color-primary); }
.article-title { color: var(--color-secondary); }
`,
  },
  {
    id: "wp.theme-json",
    name: "theme.json",
    contentType: "application/json",
    body: `{
  "$schema": "https://schemas.wp.org/trunk/theme.json",
  "version": 2,
  "settings": {
    "color": {
      "palette": [
        { "slug": "primary", "color": "{{primaryColor}}", "name": "Primary" },
        { "slug": "secondary", "color": "{{secondaryColor}}", "name": "Secondary" }
      ]
    },
    "layout": { "contentSize": "800px", "wideSize": "1200px" }
  },
  "custom": {
    "generatedBy": "Telemax AI Factory",
    "generatorVersion": "{{generatorVersion}}"
  }
}
`,
  },
  {
    id: "wp.functions",
    name: "functions.php",
    contentType: "application/x-php",
    body: `<?php
/**
 * {{themeName}} — theme bootstrap.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * PROJECT SCAFFOLD — not production WordPress code. Review before use.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

define( 'TELEMAX_NEWS_THEME_VERSION', '{{generatorVersion}}' );
define( 'TELEMAX_NEWS_GENERATED_AT', '{{generatedAt}}' );

require_once get_template_directory() . '/inc/seo.php';
require_once get_template_directory() . '/inc/schema.php';
require_once get_template_directory() . '/inc/widgets.php';
require_once get_template_directory() . '/inc/sitemap.php';

add_action( 'after_setup_theme', function () {
  add_theme_support( 'title-tag' );
  add_theme_support( 'post-thumbnails' );
  add_theme_support( 'html5', array( 'search-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
  register_nav_menus( array( 'primary' => 'Primary Menu', 'footer' => 'Footer Menu' ) );
} );

add_action( 'wp_enqueue_scripts', function () {
  $version = TELEMAX_NEWS_THEME_VERSION;
  wp_enqueue_style( '{{themeSlug}}-main', get_template_directory_uri() . '/assets/css/main.css', array(), $version );
  wp_enqueue_script( '{{themeSlug}}-main', get_template_directory_uri() . '/assets/js/main.js', array(), $version, true );
} );
`,
  },
];
