<?php
/**
 * Vivere Magazine — Schema.org helpers (NewsMediaOrganization).
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'wp_head', function () {
  $data = array(
    '@context' => 'https://schema.org',
    '@type'    => 'NewsMediaOrganization',
    'name'     => 'Vivere Magazine',
    'url'      => 'https://www.viveremagazine.example',
  );
  echo '<script type="application/ld+json">' . wp_json_encode( $data ) . '</script>';
} );
