<?php
/**
 * Vivere Magazine — SEO helpers.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'wp_head', function () {
  $description = is_singular() ? wp_strip_all_tags( get_the_excerpt() ) : 'Vivere Magazine — Magazine lifestyle: moda, benessere, viaggi, food e tendenze. Read the latest news, analysis and stories.';
  printf( '<meta name="description" content="%s" />' . "\n", esc_attr( $description ) );
  printf( '<link rel="canonical" href="%s" />' . "\n", esc_url( home_url( add_query_arg( array() ) ) ) );
}, 1 );
