<?php
/**
 * Vivere Magazine — widget areas.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Registered areas: sidebar-main, footer-1, footer-2, footer-3
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'widgets_init', function () {
  $areas = array( 'sidebar-main', 'footer-1', 'footer-2', 'footer-3' );
  foreach ( $areas as $area ) {
    register_sidebar( array(
      'id'   => $area,
      'name' => ucwords( str_replace( '-', ' ', $area ) ),
    ) );
  }
} );
