<?php
/**
 * Il Corriere della Sera Nuovo — component: Author Box.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Category: meta · Regions: content.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<section class="c-author-box" data-component="author-box" role="region" aria-label="Author Box">
  <meta itemprop="type" content="Person" />
  <figure class="c-author-box__media">
    <img loading="lazy" decoding="async" width="800" height="450" src="" alt="" />
  </figure>
  <!-- TODO: implement the "Author Box" component -->
</section>
