<?php
/**
 * Il Corriere della Sera Nuovo — component: Gallery.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Category: media · Regions: content.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<section class="c-gallery" data-component="gallery" role="group" aria-label="Gallery">
  <meta itemprop="type" content="ImageGallery" />
  <figure class="c-gallery__media">
    <img loading="lazy" decoding="async" width="800" height="450" src="" alt="" />
  </figure>
  <!-- TODO: implement the "Gallery" component -->
</section>
