<?php
/**
 * TGMAX — NewsArticle JSON-LD for single posts.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
$schema = array(
  '@context'      => 'https://schema.org',
  '@type'         => 'NewsArticle',
  'headline'      => get_the_title(),
  'datePublished' => get_the_date( 'c' ),
  'dateModified'  => get_the_modified_date( 'c' ),
  'author'        => array( '@type' => 'Person', 'name' => get_the_author() ),
  'publisher'     => array( '@type' => 'Organization', 'name' => 'TGMAX' ),
);
?>
<script type="application/ld+json"><?php echo wp_json_encode( $schema ); ?></script>
