<?php
/**
 * Gruppo AIR Blog — primary navigation menu.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Categories: Novità, Casi Studio, Cultura d'Impresa, Comunicati
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<nav class="primary-navigation" aria-label="Primary">
  <ul class="menu">
        <li class="menu-item"><a href="/">Home</a></li>
        <li class="menu-item"><a href="/category/novita">Novità</a></li>
        <li class="menu-item"><a href="/category/casi-studio">Casi Studio</a></li>
  </ul>
</nav>
