<?php
/**
 * Il Corriere della Sera Nuovo — Open Graph / Twitter meta tags.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<meta property="og:site_name" content="Il Corriere della Sera Nuovo" />
<meta property="og:type" content="website" />
<meta property="og:description" content="Il Corriere della Sera Nuovo — Quotidiano nazionale di informazione: economia, esteri, politica e approfondimenti. Read the latest news, analysis and stories." />
<meta property="og:locale" content="it_IT" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="Il Corriere della Sera Nuovo" />
