<?php
/**
 * Vivere Magazine — footer.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<footer class="site-footer">
  <div class="site-container">
    <nav class="footer-widgets">
      <?php if ( is_active_sidebar( 'footer-1' ) ) { dynamic_sidebar( 'footer-1' ); } ?>
      <?php if ( is_active_sidebar( 'footer-2' ) ) { dynamic_sidebar( 'footer-2' ); } ?>
      <?php if ( is_active_sidebar( 'footer-3' ) ) { dynamic_sidebar( 'footer-3' ); } ?>
    </nav>
    <p class="copyright">&copy; 2026 Vivere Magazine. All rights reserved.</p>
  </div>
</footer>
<?php wp_footer(); ?>
</body>
</html>
