<?php
/**
 * Vivere Magazine — blog posts index (news river).
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Generated at: 2026-08-01T12:00:00.000Z · Artifact metadata is catalogued in .telemax/manifest.json.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>
<main class="site-container home-posts">
  <header class="page-heading"><h1><?php bloginfo( 'name' ); ?> — Latest</h1></header>
  <div class="posts-river">
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
      <article <?php post_class( 'post-card' ); ?>>
        <h2 class="article-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
        <?php the_excerpt(); ?>
      </article>
    <?php endwhile; else : ?>
      <p class="empty">No posts yet.</p>
    <?php endif; ?>
  </div>
  <?php the_posts_pagination(); ?>
  <?php get_sidebar(); ?>
</main>
<?php get_footer(); ?>
