<?php
/**
 * Vivere Magazine — single article layout.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>
<main class="site-container">
  <?php while ( have_posts() ) : the_post(); ?>
    <article <?php post_class( 'single-article' ); ?>>
      <h1 class="article-title"><?php the_title(); ?></h1>
      <?php get_template_part( 'template-parts/schema/newsarticle' ); ?>
      <div class="article-body"><?php the_content(); ?></div>
      <?php get_template_part( 'template-parts/ads/ad-in-article' ); ?>
    </article>
  <?php endwhile; ?>
  <?php get_sidebar(); ?>
</main>
<?php get_footer(); ?>
