<?php
/**
 * Gruppo AIR Blog — component: Hero.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Category: hero · Regions: hero.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<section class="c-hero" data-component="hero" role="region" aria-label="Hero">
  <meta itemprop="type" content="NewsArticle" />
  <figure class="c-hero__media">
    <img loading="lazy" decoding="async" width="800" height="450" src="" alt="" />
  </figure>
  <!-- TODO: implement the "Hero" component -->
</section>
