<?php
/**
 * Vivere Magazine — primary navigation menu.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Categories: Moda, Benessere, Viaggi, Food, Tendenze
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<nav class="primary-navigation" aria-label="Primary">
  <ul class="menu">
        <li class="menu-item"><a href="/">Home</a></li>
        <li class="menu-item"><a href="/category/moda">Moda</a></li>
        <li class="menu-item"><a href="/category/viaggi">Viaggi</a></li>
        <li class="menu-item"><a href="/category/food">Food</a></li>
  </ul>
</nav>
