<?php
/**
 * Vivere Magazine — sidebar ad slot.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — wire your ad manager during completion.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<div class="ad-slot ad-sidebar" data-ad-slot="sidebar">
  <!-- TODO: inject ad tag for the "sidebar" slot -->
</div>
