<?php
/**
 * TGMAX — theme bootstrap.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — not production WordPress code. Review before use.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

define( 'TELEMAX_NEWS_THEME_VERSION', '0.1.0' );
define( 'TELEMAX_NEWS_GENERATED_AT', '2026-08-01T12:00:00.000Z' );

require_once get_template_directory() . '/inc/seo.php';
require_once get_template_directory() . '/inc/schema.php';
require_once get_template_directory() . '/inc/widgets.php';
require_once get_template_directory() . '/inc/sitemap.php';

add_action( 'after_setup_theme', function () {
  add_theme_support( 'title-tag' );
  add_theme_support( 'post-thumbnails' );
  add_theme_support( 'html5', array( 'search-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
  register_nav_menus( array( 'primary' => 'Primary Menu', 'footer' => 'Footer Menu' ) );
} );

add_action( 'wp_enqueue_scripts', function () {
  $version = TELEMAX_NEWS_THEME_VERSION;
  wp_enqueue_style( 'tgmax-main', get_template_directory_uri() . '/assets/css/main.css', array(), $version );
  wp_enqueue_script( 'tgmax-main', get_template_directory_uri() . '/assets/js/main.js', array(), $version, true );
} );
