<?php
/**
 * TGMAX — header.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!doctype html>
<html lang="it_IT" <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo( 'charset' ); ?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <?php get_template_part( 'template-parts/seo/meta-tags' ); ?>
  <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<header class="site-header">
  <div class="site-container">
    <a class="site-brand" href="https://www.tgmax.it">TGMAX</a>
    <p class="site-tagline">Il portale di news della TV locale abruzzese: cronaca, politica, sport e cultura.</p>
    <?php get_template_part( 'template-parts/navigation' ); ?>
  </div>
</header>
