<?php
/**
 * TGMAX — static page layout.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
?>
<main class="site-container">
  <?php while ( have_posts() ) : the_post(); ?>
    <article <?php post_class( 'static-page' ); ?>>
      <h1 class="article-title"><?php the_title(); ?></h1>
      <div class="page-body"><?php the_content(); ?></div>
    </article>
  <?php endwhile; ?>
</main>
<?php get_footer(); ?>
