<?php
/**
 * TGMAX — primary sidebar.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<aside class="site-sidebar">
  <?php get_template_part( 'template-parts/ads/ad-sidebar' ); ?>
  <?php if ( is_active_sidebar( 'sidebar-main' ) ) { dynamic_sidebar( 'sidebar-main' ); } ?>
</aside>
