<?php
/**
 * Sprint Sport — sitemap configuration.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * PROJECT SCAFFOLD — tune the core sitemap provider on completion.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

add_filter( 'wp_sitemaps_max_urls', function () { return 2000; } );
// TODO: register a dedicated news sitemap provider during completion.
