/**
 * Component Registry blueprint: every generatable news component, with its
 * category, the layout regions it may appear in, accessibility role, Schema.org
 * type and whether it carries lazy-loaded media. The registry also generates a
 * scaffold template-part for each component.
 */
import type { GeneratorTemplate } from "@telemax/generator-engine";

export type ComponentCategory =
  | "hero"
  | "list"
  | "alert"
  | "media"
  | "meta"
  | "engagement"
  | "advertising";

export interface ComponentSpec {
  readonly id: string;
  readonly name: string;
  readonly category: ComponentCategory;
  readonly regions: readonly string[];
  readonly ariaRole: string;
  readonly hasMedia: boolean;
  readonly schemaType?: string;
}

/** The full registry of generatable components. */
export function componentRegistry(): readonly ComponentSpec[] {
  return [
    {
      id: "hero",
      name: "Hero",
      category: "hero",
      regions: ["hero"],
      ariaRole: "region",
      hasMedia: true,
      schemaType: "NewsArticle",
    },
    {
      id: "card-news",
      name: "Card News",
      category: "list",
      regions: ["content", "sidebar"],
      ariaRole: "article",
      hasMedia: true,
      schemaType: "NewsArticle",
    },
    {
      id: "breaking-news",
      name: "Breaking News",
      category: "alert",
      regions: ["header", "hero"],
      ariaRole: "alert",
      hasMedia: false,
    },
    {
      id: "live-banner",
      name: "Live Banner",
      category: "alert",
      regions: ["header", "hero"],
      ariaRole: "status",
      hasMedia: false,
    },
    {
      id: "video-block",
      name: "Video Block",
      category: "media",
      regions: ["content", "hero"],
      ariaRole: "region",
      hasMedia: true,
      schemaType: "VideoObject",
    },
    {
      id: "gallery",
      name: "Gallery",
      category: "media",
      regions: ["content"],
      ariaRole: "group",
      hasMedia: true,
      schemaType: "ImageGallery",
    },
    {
      id: "related-articles",
      name: "Related Articles",
      category: "list",
      regions: ["content"],
      ariaRole: "complementary",
      hasMedia: true,
    },
    {
      id: "author-box",
      name: "Author Box",
      category: "meta",
      regions: ["content"],
      ariaRole: "region",
      hasMedia: true,
      schemaType: "Person",
    },
    {
      id: "breadcrumb",
      name: "Breadcrumb",
      category: "meta",
      regions: ["content"],
      ariaRole: "navigation",
      hasMedia: false,
      schemaType: "BreadcrumbList",
    },
    {
      id: "social-share",
      name: "Social Share",
      category: "engagement",
      regions: ["content"],
      ariaRole: "group",
      hasMedia: false,
    },
    {
      id: "newsletter",
      name: "Newsletter",
      category: "engagement",
      regions: ["content", "sidebar", "footer"],
      ariaRole: "form",
      hasMedia: false,
    },
    {
      id: "comments",
      name: "Comments",
      category: "engagement",
      regions: ["content"],
      ariaRole: "region",
      hasMedia: false,
    },
    {
      id: "banner-adv",
      name: "Banner ADV",
      category: "advertising",
      regions: ["header", "sidebar", "content", "footer"],
      ariaRole: "complementary",
      hasMedia: false,
    },
  ];
}

/** Generate a scaffold template-part for a component. */
function componentScaffold(spec: ComponentSpec): GeneratorTemplate {
  const media = spec.hasMedia
    ? `\n  <figure class="c-${spec.id}__media">\n    <img loading="lazy" decoding="async" width="800" height="450" src="" alt="" />\n  </figure>`
    : "";
  const schema =
    spec.schemaType !== undefined
      ? `\n  <meta itemprop="type" content="${spec.schemaType}" />`
      : "";
  const body = `<?php
/**
 * {{themeName}} — component: ${spec.name}.
 * Generated by Telemax AI Factory · WordPress News generator v{{generatorVersion}}.
 * Category: ${spec.category} · Regions: ${spec.regions.join(", ")}.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<section class="c-${spec.id}" data-component="${spec.id}" role="${spec.ariaRole}" aria-label="${spec.name}">${schema}${media}
  <!-- TODO: implement the "${spec.name}" component -->
</section>
`;
  return {
    id: `wp.component.${spec.id}`,
    name: `template-parts/components/${spec.id}.php`,
    contentType: "application/x-php",
    body,
  };
}

/** Scaffold template-parts for every registered component. */
export function componentScaffolds(): readonly GeneratorTemplate[] {
  return componentRegistry().map(componentScaffold);
}
