<?php
/**
 * Vivere Magazine — Open Graph / Twitter meta tags.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<meta property="og:site_name" content="Vivere Magazine" />
<meta property="og:type" content="website" />
<meta property="og:description" content="Vivere Magazine — Magazine lifestyle: moda, benessere, viaggi, food e tendenze. Read the latest news, analysis and stories." />
<meta property="og:locale" content="it_IT" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="Vivere Magazine" />
