<?php
/**
 * Sprint Sport — component: Banner ADV.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Category: advertising · Regions: header, sidebar, content, footer.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<section class="c-banner-adv" data-component="banner-adv" role="complementary" aria-label="Banner ADV">
  <!-- TODO: implement the "Banner ADV" component -->
</section>
