<?php
/**
 * Sprint Sport — component: Breaking News.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Category: alert · Regions: header, hero.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<section class="c-breaking-news" data-component="breaking-news" role="alert" aria-label="Breaking News">
  <!-- TODO: implement the "Breaking News" component -->
</section>
