<?php
/**
 * Sprint Sport — component: Card News.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Category: list · Regions: content, sidebar.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<section class="c-card-news" data-component="card-news" role="article" aria-label="Card News">
  <meta itemprop="type" content="NewsArticle" />
  <figure class="c-card-news__media">
    <img loading="lazy" decoding="async" width="800" height="450" src="" alt="" />
  </figure>
  <!-- TODO: implement the "Card News" component -->
</section>
