<?php
/**
 * Sprint Sport — component: Related Articles.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Category: list · Regions: content.
 * PROJECT SCAFFOLD — not production WordPress code.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<section class="c-related-articles" data-component="related-articles" role="complementary" aria-label="Related Articles">
  <figure class="c-related-articles__media">
    <img loading="lazy" decoding="async" width="800" height="450" src="" alt="" />
  </figure>
  <!-- TODO: implement the "Related Articles" component -->
</section>
