<?php
/**
 * Il Corriere della Sera Nuovo — primary navigation menu.
 * Generated by Telemax AI Factory · WordPress News generator v0.1.0.
 * Categories: Politica, Economia, Esteri, Cultura, Opinioni, Editoriali
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<nav class="primary-navigation" aria-label="Primary">
  <ul class="menu">
        <li class="menu-item"><a href="/">Home</a></li>
        <li class="menu-item"><a href="/category/politica">Politica</a></li>
        <li class="menu-item"><a href="/category/economia">Economia</a></li>
        <li class="menu-item"><a href="/category/esteri">Esteri</a></li>
  </ul>
</nav>
